import { FaceLandmarker, FilesetResolver } from 'https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/+esm';

const $=id=>document.getElementById(id), video=$('video'), canvas=$('canvas'), ctx=canvas.getContext('2d'), stage=$('stage'), statusEl=$('status'), stageHint=$('stageHint');
const CARD_WIDTH_MM=85.6, STORAGE_KEY='pd-meter-measurements-v1';
let stream=null,facingMode='user',imageReady=false,faceLandmarker=null,autoEyes=null,eyes=null,nose=null,cardPoints=[],dragTarget=null,sourceImage=null,measurementSaved=false,saveTimer=null;

const dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
const avg=points=>({x:points.reduce((s,p)=>s+p.x,0)/points.length,y:points.reduce((s,p)=>s+p.y,0)/points.length});
const setStatus=text=>statusEl.textContent=text;
function canvasPoint(e){const r=canvas.getBoundingClientRect(),p=e.touches?.[0]||e.changedTouches?.[0]||e;return{x:(p.clientX-r.left)*canvas.width/r.width,y:(p.clientY-r.top)*canvas.height/r.height};}
function near(p,t,r=28){return t&&dist(p,t)<=r*(canvas.width/canvas.clientWidth);}

async function startCamera(){
  stopCamera(false);
  try{
    stream=await navigator.mediaDevices.getUserMedia({video:{facingMode,width:{ideal:1920},height:{ideal:1080}},audio:false});
    video.srcObject=stream; await video.play(); video.hidden=false; canvas.style.position='absolute'; stageHint.classList.add('hidden');
    $('capture').disabled=false; $('switchCamera').disabled=false; $('stopCamera').disabled=false; $('retake').disabled=true; $('analyze').disabled=true;
    setStatus('Tartsd a kártyát az arcod síkjában, nézz a kamerába, majd készíts képet.');
  }catch(error){setStatus(`A kamera nem indítható: ${error.message}`);}
}
function stopCamera(showMessage=true){
  stream?.getTracks().forEach(t=>t.stop()); stream=null; video.srcObject=null;
  $('capture').disabled=true; $('switchCamera').disabled=true; $('stopCamera').disabled=true;
  if(showMessage){video.hidden=true; stageHint.classList.remove('hidden'); stageHint.textContent='A kamera leállítva.'; setStatus('A kamera leállítva.');}
}
async function switchCamera(){facingMode=facingMode==='user'?'environment':'user';await startCamera();}
function sizeCanvas(w,h){canvas.width=w;canvas.height=h;canvas.style.position='relative';stage.style.minHeight='0';}
function resetMeasurement(){cardPoints=[];autoEyes=null;eyes=null;nose=null;dragTarget=null;measurementSaved=false;clearTimeout(saveTimer);$('calibration').classList.add('hidden');$('results').classList.add('hidden');$('saveState').textContent='A megfelelő mérés automatikusan mentésre kerül.';updateCardState();}
function capture(){
  if(!video.videoWidth)return; sizeCanvas(video.videoWidth,video.videoHeight); ctx.save(); if(facingMode==='user'){ctx.translate(canvas.width,0);ctx.scale(-1,1);} ctx.drawImage(video,0,0,canvas.width,canvas.height);ctx.restore();
  sourceImage=ctx.getImageData(0,0,canvas.width,canvas.height);imageReady=true;video.hidden=true;stopCamera(false);resetMeasurement();redraw();
  $('capture').disabled=true;$('retake').disabled=false;$('analyze').disabled=false;setStatus('Kép elkészült. Indítsd el az arcfelismerést.');
}
function loadFile(file){if(!file)return;const img=new Image();img.onload=()=>{const max=2200,s=Math.min(1,max/Math.max(img.naturalWidth,img.naturalHeight));sizeCanvas(Math.round(img.naturalWidth*s),Math.round(img.naturalHeight*s));ctx.drawImage(img,0,0,canvas.width,canvas.height);sourceImage=ctx.getImageData(0,0,canvas.width,canvas.height);imageReady=true;video.hidden=true;stopCamera(false);resetMeasurement();redraw();stageHint.classList.add('hidden');$('retake').disabled=false;$('analyze').disabled=false;URL.revokeObjectURL(img.src);setStatus('Kép betöltve. Indítsd el az arcfelismerést.');};img.src=URL.createObjectURL(file);}
async function ensureModel(){if(faceLandmarker)return;setStatus('Arcfelismerő modell betöltése…');const vision=await FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22-rc.20250304/wasm');faceLandmarker=await FaceLandmarker.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_landmarker/face_landmarker/float16/1/face_landmarker.task',delegate:'GPU'},runningMode:'IMAGE',numFaces:1});}
async function analyze(){
  if(!imageReady)return;
  try{await ensureModel();const bitmap=await createImageBitmap(new ImageData(sourceImage,canvas.width,canvas.height)),result=faceLandmarker.detect(bitmap);bitmap.close();const lm=result.faceLandmarks?.[0];if(!lm){setStatus('Nem találtam arcot. Készíts élesebb, szemből készült képet jobb fényben.');return;}const px=p=>({x:p.x*canvas.width,y:p.y*canvas.height});const a=avg([468,469,470,471,472].map(i=>px(lm[i]))),b=avg([473,474,475,476,477].map(i=>px(lm[i]))),ordered=[a,b].sort((p,q)=>p.x-q.x);autoEyes={left:{...ordered[0]},right:{...ordered[1]}};eyes=structuredClone(autoEyes);nose=px(lm[168]);$('calibration').classList.remove('hidden');$('results').classList.remove('hidden');setStatus('Arc felismerve. Jelöld meg a referencia négy sarkát.');redraw();updateResults();}catch(error){setStatus(`Az elemzés sikertelen: ${error.message}`);}
}
function drawPoint(p,color,label){const r=Math.max(7,canvas.width/170);ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fillStyle=color;ctx.fill();ctx.lineWidth=Math.max(2,canvas.width/700);ctx.strokeStyle='#fff';ctx.stroke();ctx.font=`600 ${Math.max(14,canvas.width/70)}px system-ui`;ctx.fillStyle='#fff';ctx.fillText(label,p.x+r+5,p.y-r-2);}
function referenceLength(){return document.querySelector('input[name="reference"]:checked').value==='card'?CARD_WIDTH_MM:Number($('customLength').value);}
function scaleMmPerPx(){if(cardPoints.length!==4)return null;const top=dist(cardPoints[0],cardPoints[1]),bottom=dist(cardPoints[3],cardPoints[2]),width=(top+bottom)/2;return width>0?referenceLength()/width:null;}
function currentMeasurement(){const scale=scaleMmPerPx();if(!scale||!eyes)return null;const total=dist(eyes.left,eyes.right)*scale,centerX=nose?.x??(eyes.left.x+eyes.right.x)/2,right=Math.abs(centerX-eyes.left.x)*scale,left=Math.abs(eyes.right.x-centerX)*scale;const top=dist(cardPoints[0],cardPoints[1]),bottom=dist(cardPoints[3],cardPoints[2]),skew=Math.abs(top-bottom)/((top+bottom)/2);return{total,right,left,skew};}
function redraw(){if(!sourceImage)return;ctx.putImageData(sourceImage,0,0);if(cardPoints.length){ctx.lineWidth=Math.max(3,canvas.width/500);ctx.strokeStyle='#f59e0b';ctx.beginPath();cardPoints.forEach((p,i)=>i?ctx.lineTo(p.x,p.y):ctx.moveTo(p.x,p.y));if(cardPoints.length===4)ctx.closePath();ctx.stroke();cardPoints.forEach((p,i)=>drawPoint(p,'#f59e0b',String(i+1)));}if(eyes){const m=currentMeasurement();ctx.strokeStyle='#22c55e';ctx.lineWidth=Math.max(4,canvas.width/400);ctx.beginPath();ctx.moveTo(eyes.left.x,eyes.left.y);ctx.lineTo(eyes.right.x,eyes.right.y);ctx.stroke();if(m){const mid={x:(eyes.left.x+eyes.right.x)/2,y:(eyes.left.y+eyes.right.y)/2};const text=`${m.total.toFixed(1)} mm`;ctx.font=`700 ${Math.max(18,canvas.width/55)}px system-ui`;const w=ctx.measureText(text).width;ctx.fillStyle='rgba(3,7,18,.82)';ctx.fillRect(mid.x-w/2-10,mid.y-42,w+20,32);ctx.fillStyle='#fff';ctx.fillText(text,mid.x-w/2,mid.y-17);}drawPoint(eyes.left,'#22c55e','P');drawPoint(eyes.right,'#22c55e','P');}if(nose){ctx.setLineDash([12,10]);ctx.strokeStyle='#60a5fa';ctx.lineWidth=Math.max(2,canvas.width/700);ctx.beginPath();ctx.moveTo(nose.x,Math.max(0,nose.y-canvas.height*.12));ctx.lineTo(nose.x,Math.min(canvas.height,nose.y+canvas.height*.13));ctx.stroke();ctx.setLineDash([]);}}
function updateCardState(){$('cardState').textContent=`${cardPoints.length}/4 sarok megadva${cardPoints.length===4?' – kalibráció kész.':'.'}`;updateResults();}
function validMeasurement(m){return m&&m.total>=50&&m.total<=80&&m.skew<=.12&&Math.abs(m.right-m.left)<=6;}
function updateResults(){
  const m=currentMeasurement();if(!m){['pdTotal','pdRight','pdLeft'].forEach(id=>$(id).textContent='–');$('qualityText').textContent='Kalibráció szükséges';redraw();return;}
  $('pdTotal').textContent=m.total.toFixed(1);$('pdRight').textContent=m.right.toFixed(1);$('pdLeft').textContent=m.left.toFixed(1);
  let quality='Mérés kész';if(m.total<50||m.total>80)quality='Szokatlan eredmény – ellenőrizd a pontokat';else if(m.skew>.12)quality='A referencia perspektívája túl nagy';else if(Math.abs(m.right-m.left)>6)quality='Ellenőrizd az orr-középvonalat';$('qualityText').textContent=quality;redraw();
  clearTimeout(saveTimer);if(validMeasurement(m)&&!measurementSaved)saveTimer=setTimeout(()=>saveMeasurement(m),900);
}
function playSuccess(){try{const ac=new (window.AudioContext||window.webkitAudioContext)(),o=ac.createOscillator(),g=ac.createGain();o.type='sine';o.frequency.setValueAtTime(660,ac.currentTime);o.frequency.exponentialRampToValueAtTime(990,ac.currentTime+.16);g.gain.setValueAtTime(.0001,ac.currentTime);g.gain.exponentialRampToValueAtTime(.18,ac.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,ac.currentTime+.24);o.connect(g).connect(ac.destination);o.start();o.stop(ac.currentTime+.25);}catch{}}
function getHistory(){try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');}catch{return[];}}
function saveMeasurement(m){const list=getHistory();list.push({total:+m.total.toFixed(1),right:+m.right.toFixed(1),left:+m.left.toFixed(1),time:Date.now()});localStorage.setItem(STORAGE_KEY,JSON.stringify(list.slice(-30)));measurementSaved=true;$('saveState').textContent='Mérés automatikusan elmentve.';playSuccess();renderHistory();}
function renderHistory(){const list=getHistory();if(!list.length){$('avgTotal').textContent=$('avgRight').textContent=$('avgLeft').textContent='–';$('historyState').textContent='Nincs mentett mérés.';return;}const mean=k=>list.reduce((s,x)=>s+x[k],0)/list.length;$('avgTotal').textContent=mean('total').toFixed(1);$('avgRight').textContent=mean('right').toFixed(1);$('avgLeft').textContent=mean('left').toFixed(1);$('historyState').textContent=`${list.length} mentett mérés átlaga. Legfeljebb az utolsó 30 mérés marad meg ezen az eszközön.`;}
function pointerDown(e){if(!imageReady)return;const p=canvasPoint(e);if(eyes&&near(p,eyes.left))dragTarget={type:'eye',key:'left'};else if(eyes&&near(p,eyes.right))dragTarget={type:'eye',key:'right'};else{const i=cardPoints.findIndex(cp=>near(p,cp));if(i>=0)dragTarget={type:'card',index:i};else if(cardPoints.length<4){cardPoints.push(p);updateCardState();redraw();}}if(dragTarget)e.preventDefault();}
function pointerMove(e){if(!dragTarget)return;e.preventDefault();measurementSaved=false;$('saveState').textContent='A módosított mérés automatikusan mentésre kerül.';const p=canvasPoint(e);if(dragTarget.type==='eye')eyes[dragTarget.key]=p;else cardPoints[dragTarget.index]=p;redraw();updateResults();}
function pointerUp(){dragTarget=null;}

$('startCamera').addEventListener('click',startCamera);$('stopCamera').addEventListener('click',()=>stopCamera(true));$('switchCamera').addEventListener('click',switchCamera);$('capture').addEventListener('click',capture);$('retake').addEventListener('click',()=>{resetMeasurement();sourceImage=null;imageReady=false;ctx.clearRect(0,0,canvas.width,canvas.height);startCamera();});$('analyze').addEventListener('click',analyze);$('fileInput').addEventListener('change',e=>loadFile(e.target.files[0]));$('resetCard').addEventListener('click',()=>{cardPoints=[];measurementSaved=false;updateCardState();redraw();});$('resetEyes').addEventListener('click',()=>{if(autoEyes){eyes=structuredClone(autoEyes);measurementSaved=false;redraw();updateResults();}});$('clearHistory').addEventListener('click',()=>{localStorage.removeItem(STORAGE_KEY);renderHistory();});document.querySelectorAll('input[name="reference"]').forEach(el=>el.addEventListener('change',()=>{$('customLengthWrap').classList.toggle('hidden',el.value!=='custom'||!el.checked);measurementSaved=false;updateResults();}));$('customLength').addEventListener('input',()=>{measurementSaved=false;updateResults();});canvas.addEventListener('pointerdown',pointerDown);canvas.addEventListener('pointermove',pointerMove);canvas.addEventListener('pointerup',pointerUp);canvas.addEventListener('pointercancel',pointerUp);canvas.addEventListener('pointerleave',pointerUp);window.addEventListener('beforeunload',()=>stopCamera(false));renderHistory();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
